### ISSUE TITLE
Strip HTML tags

### ISSUE THREAD

**Issue by spellsmith** [derula/swlrp-server#34]
Currently the mod appears to allow HTML tags, including in the Character Name and in all editable fields.  Given we're using WYSIWYG already, it would probably be best to strip out any incoming HTML tags to 1) keep things clean and 2) prevent attempts at malicious code.

**Comment by derula** [comment]
Just to make sure we're talking about the same thing: In the name fields and the user properties, HTML tags can be entered, but they will just be shown as their literal values instead of being interpreted as HTML. I set examples up on the test server specifically to show that the user _cannot_ use HTML in those fields. I believe this behavior is correct, and stripping it out will not provide any increased security benefit. However, doing so _can_ lead to weird bugs and confusion for the users. So I'm against stripping HTML tags, it just makes little sense to me.

See also:

- https://stackoverflow.com/questions/7232793/should-i-use-both-striptags-and-htmlspecialchars-to-prevent-xss
- https://www.reddit.com/r/PHP/comments/nj5t0/what_everyone_should_know_about_strip_tags/

Of course, if you _do_ find a place where you can enter HTML and it will actually _work_ - like, say, an eye color of \<b>red\</b> will actually appear as **red** - then this would be a bug and need to be fixed.

**Comment by spellsmith** [comment]
You're correct, that's what I was thinking, but I agree with your explanation and agree with keeping functionality as is.  Closing issue!
