### ISSUE TITLE
Error 404 Defaulting to Logged-In Character?

### ISSUE THREAD

**Issue by spellsmith** [derula/swlrp-server#35]
While in edit mode, loggedin, testing things on John "<b>Test</b>":

https://swlrp.incertitu.de/edit/1

I attempted to swap to another character to bring up the 404 page to see what it displayed.  

However, ALL various URLs seem to point back to John

https://swlrp.incertitu.de/edit/5
https://swlrp.incertitu.de/edit/405
https://swlrp.incertitu.de/edit/Sanneke
https://swlrp.incertitu.de/edit/Mewf
https://swlrp.incertitu.de/edit/asdfasdf

All maintain John's page and information and keeps me logged in.

Unsure if intentional ('test server') or not.  I don't recall it having this behavior before.

**Comment by derula** [comment]
...wait what? This worked when I tested it locally. Weird. I'll have a look, maybe the test server isn't up to date.

**Comment by derula** [comment]
Okay, test server wasn't up to date, sorry about that.

The three links with names still work, but that's because the name will be cast to an integer, which will result in zero, which will be interpreted as "no ID specified," thus leading to the same page as edit/ without an ID. It doesn't break anything, but if you think it's important to show an error in that case, I could add that.

**Comment by spellsmith** [comment]
I would personally add it, as it might be a useful diagnostic in case Funcom ever does anything wonky with character IDs or we run into some odd special case scenario.  Past that, I think this is good to close!

**Comment by derula** [comment]
Entering a string as character ID will lead to error page now.
